### ISSUE TITLE
Example from README produces an error

### ISSUE THREAD

**Issue by avi12** [fregante/chrome-webstore-upload#100]
```ts
const { uploadState, itemError } = await client.uploadExisting(fs.createReadStream(zip));
```
produces a TypeScript error:
```
TS2345: Argument of type ReadStream is not assignable to parameter of type ReadableStream<any>
```
Basically,
https://github.com/fregante/chrome-webstore-upload/blob/858ffb7e88315c74efbb0b2005f4acb6a79a8f48/source/index.ts#L72

expects a `ReadableStream` whereas `fs.createReadStream` returns a [ReadStream](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c32c8c1a24a6cbfd8b2b44b4de718c6d07eef71c/types/node/fs.d.ts#L3911)

**Comment by fregante** [comment]
Thanks! This seems to be a type error since both ReadStream and ReadableStream are passed in the cli:

https://github.com/fregante/chrome-webstore-upload-cli/blob/8d53b9e45c1f87ce926f5933451081a0d5172864/wrapper.js#L10-L12

With yazl using `ReadableStream`


https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c32c8c1a24a6cbfd8b2b44b4de718c6d07eef71c/types/yazl/index.d.ts#L32

I'll send a PR

**Comment by fregante** [comment]
I fixed the types for now. Does it work eventually? It's entirely possible that nobody uses zip uploads this way so it has been broken for a while. Let me know.

**Comment by avi12** [comment]
Now I get
```
error TS2307: Cannot find module 'type-fest' or its corresponding type declarations.
```
which refers to
https://github.com/fregante/chrome-webstore-upload/blob/858ffb7e88315c74efbb0b2005f4acb6a79a8f48/source/index.ts#L5

**Comment by fregante** [comment]
Fixed

**Comment by fregante** [comment]
The TS conversion was recent (https://github.com/fregante/chrome-webstore-upload/pull/84) so the types haven't seen much testing in the real world.

**Comment by avi12** [comment]
Thanks for the quick fixes!

**Comment by avi12** [comment]
There is another case of [incompatible types](https://developer.chrome.com/docs/webstore/api#resource) where `uploadExisting` returns a string `uploadState` and an object array `itemError` while both are treated in TypeScript as JSONs

**Comment by avi12** [comment]
@fregante I'd appreciate it if you could solve the type discrepancies
