### ISSUE TITLE
Version with node-fetch (Fixes `invalid grant_type` with newer got versions)

### ISSUE THREAD

**Issue by rubenwardy** [fregante/chrome-webstore-upload#50]
There's a problem with the got@11.8.2 library that is causing an the fetchToken API call to return :

```js
{
	error: 'unsupported_grant_type',
    error_description: 'Invalid grant_type: '
}
```

I've fixed this by using node-fetch instead:

```js
const fs = require("fs");
const process = require("process");
const { default: fetch, Request } = require("node-fetch");

const rootURI = "https://www.googleapis.com";
const refreshTokenURI = "https://www.googleapis.com/oauth2/v4/token";
const uploadExistingURI = id => `${rootURI}/upload/chromewebstore/v1.1/items/${id}`;
const publishURI = (id, target) => (
	`${rootURI}/chromewebstore/v1.1/items/${id}/publish?publishTarget=${target}`
);

const requiredFields = [
	"extensionId",
	"clientId",
	"refreshToken"
];

class APIClient {
	constructor(options) {
		requiredFields.forEach(field => {
			if (!options[field]) {
				throw new Error(`Option "${field}" is required`);
			}

			this[field] = options[field];
		});

		if ("clientSecret" in options) {
			this.clientSecret = options.clientSecret;
		}
	}

	async uploadExisting(readStream, token = this.fetchToken()) {
		if (!readStream) {
			throw new Error("Read stream missing");
		}

		const { extensionId } = this;

		const response = await fetch(new Request(uploadExistingURI(extensionId), {
			method: "PUT",
			headers: this._headers(await token),
			body: readStream,
		}));

		return await response.json();
	}

	async publish(target = "default", token = this.fetchToken()) {
		const { extensionId } = this;

		const response = await fetch(new Request(publishURI(extensionId, target), {
			method: "POST",
			headers: this._headers(await token),
		}));

		return await response.json();
	}

	async fetchToken() {
		const { clientId, clientSecret, refreshToken } = this;

		const response = await fetch(new Request(refreshTokenURI, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				client_id: clientId,
				client_secret: clientSecret,
				refresh_token: refreshToken,
				grant_type: "refresh_token",
			}),
		}));

		const json = await response.json();
		return json.access_token;
	}

	_headers(token) {
		return {
			Authorization: `Bearer ${token}`,
			"x-goog-api-version": "2"
		};
	}
}
```

**Comment by fregante** [comment]
It's more likely that the input data was incorrect/incomplete because the library has been in continuous use in my repos for months without change.

However if you'd like to open a PR to replace `got` with `node-fetch` I'd accept it. I hope to release a new major version this or next month.

**Comment by rubenwardy** [comment]
`got` prints the body arguments in the error message, and they all look correct. My first step when reproducing this error was to check the same request with Insomnia (open source Postman), and it worked. I then replaced got with node-fetch, without changing any arguments, and that worked

I use a rolling release distro and [copied the code](https://gitlab.com/renewedtab/renewedtab/-/blob/master/utils/upload_chrome.js) rather than using this library - it seems more likely due to having a different `got` version. I used 11.8, whereas the library uses 11.5.

Obviously, it's a user error to use a different version of the library. I made this issue not because it's a bug with this library (it probably works with the correct got version) but to share my porting to node-fetch as I felt that it could be useful

**Comment by fregante** [comment]
I made several updates in this module and its CLI counterpart, including handling errors a little better: https://github.com/fregante/chrome-webstore-upload-cli/pull/55

I'd still like to replace got with `fetch` to make it lighter, so feel free to open a PR
