### ISSUE TITLE
Log deprecation of `client_secret`

### ISSUE THREAD

**Issue by fregante** [fregante/chrome-webstore-upload#53]
- Follows https://github.com/fregante/chrome-webstore-upload/pull/46

In 0.5.0 the client_secret was made unnecessary but it was kept hidden in the code in an attempt to smooth migration over, without having to recreate the keys.

At some point, far far away in the future, that code will be dropped or will break, so the module should log a CLIENT_SECRET DEPRECATED notice somewhere when received/used.

**Comment by quentin-decre** [comment]
Isn't this solved ?
Correct in the readme, but still wrong here : https://gokatz.me/blog/automate-your-chrome-extension-deployment-in-minutes/

**Comment by fregante** [comment]
By “log deprecation” I mean that if you pass the secret, this should log a warning.

**Comment by fregante** [comment]
The secret is no longer deprecated 🥲 https://github.com/fregante/chrome-webstore-upload/issues/59#issuecomment-1098874317
