### ISSUE TITLE
The examples in the readme are incorrect

### ISSUE THREAD

**Issue by fregante** [fregante/chrome-webstore-upload#54]
They refer to a `store` variable that doesn’t exist.

**Comment by quentin-decre** [comment]
You have to set it up by yourself as in readme : 
`const store = chromeWebstoreUpload({
  extensionId: 'ecnglinljpjkbgmdpeiglonddahpbkeb',
  clientId: 'xxxxxxxxxx',
  refreshToken: 'xxxxxxxxxx',
});`
