### ISSUE TITLE
Cannot use the example from the README

### ISSUE THREAD

**Issue by avi12** [fregante/chrome-webstore-upload#57]
I'm using this module as a part of [my module](/avi12/web-ext-deploy/blob/main/src/stores/chrome/chrome-deploy.ts) and I'm trying to upgrade to version 1.0.0.
I'm trying to use the example:
```js
import chromeWebstoreUpload from 'chrome-webstore-upload';

const store = chromeWebstoreUpload({
  extensionId: 'ecnglinljpjkbgmdpeiglonddahpbkeb',
  clientId: 'xxxxxxxxxx',
  refreshToken: 'xxxxxxxxxx',
});
```

Except, when calling `chromeWebstoreUpload`, I'm getting:
```
    const client = chromeWebstoreUpload({
                                                 ^
Error [ERR_REQUIRE_ESM]: require() of ES Module PATH_CHROME\node_modules\chrome-webstore-upload\index.js from PATH_MY_MODULE\src\stores\chrome\chrome-deploy.ts not supported.
Instead change the require of index.js in PATH_MY_MODULE\src\stores\chrome\chrome-deploy.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by fregante** [comment]
Refer to https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by fregante** [comment]
Typescript is converting those imports into requires due to this config: https://github.com/avi12/web-ext-deploy/blob/20609103197c08f9e95207ad22a9c45811c91aab/tsconfig.json#L6

**Comment by avi12** [comment]
I solved the issue by changing `"module": "commonjs"` to `"module": "esnext"` and following [this answer](https://github.com/TypeStrong/ts-node/issues/922#issuecomment-673155000)
Thanks a lot!
