### ISSUE TITLE
Google has deprecated OOB OAuth Flows

### ISSUE THREAD

**Issue by ColdSauce** [fregante/chrome-webstore-upload#59]
As of Feb 28th 2022, Google has [deprecated OOB OAuth flows](https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html).

Just a heads up as the documentation to get the refreshToken relies on the oob flow, and we're seeing `400`s when trying to go through that flow.

Example:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/2267038/159267249-51f170bb-0131-4ea2-b64e-662dad6b315b.png">

**Comment by louisgv** [comment]
Quite a shame since it's what the official doc for chrome web-store is using: https://developer.chrome.com/docs/webstore/using_webstore_api/

**Comment by pgamerx** [comment]
That's the reason I am unable to get my refresh token lol

**Comment by fregante** [comment]
From the linked post, it seems that the temporary fix is to add a `&ack_oob_shutdown=2022-10-03` parameter to the URL. Can anyone try? PR welcome if that works.

I think that the tokens generated this way will continue being valid, the problem here is just the process itself (which I'll have to update at some point)

**Comment by poma** [comment]
adding `&ack_oob_shutdown=2022-10-03` didn't work for me

**Comment by mismith** [comment]
> From the linked post, it seems that the temporary fix is to add a `&ack_oob_shutdown=2022-10-03` parameter to the URL. Can anyone try?

No luck for me either, sadly

**Comment by melink14** [comment]
It seems like that parameter will only suppress the warning message for existing projects; new projects are banned from using it.

**Comment by rafek1241** [comment]
FYI I tried to contact some people that are working at google via linkedin because I couldn't find a way to reach this company. Their support page is a joke for extension developers.

**Comment by melink14** [comment]
I'm inclined to agree with https://github.com/plasmo-corp/cwu/issues/12 that the way forward is to run a local server which allows you to use the loopback method as per the docs. There are many cheap ways to start a quick local server so even if there's no special support in this app we can update the documentation if someone tests out the flow!

**Comment by rafek1241** [comment]
@melink14 but what will we do after that method deprecation?

**Comment by louisgv** [comment]
@melink14 I will be working on open-sourcing the tool mentioned soon, hopefully by end of this week. Been traveling last month so got a bit jetlag still xD...

@rafek1241 the tool I'm developing will not use the loopback method, but will use the normal OAuth flow to get the refreshToken.

**Comment by rafek1241** [comment]
@louisgv 
If you need any help, contact me ;)

**Comment by melink14** [comment]
@rafek1241 The loopback method is not being deprecated for desktop apps (only for android and ios). 

@louisgv Thanks a lot for the follow up. It should be quite useful! But are you sure you're not using the loopback method? I can't see any other type of recommended flow for desktop applications that were using oob before: https://developers.google.com/identity/protocols/oauth2/native-app#step-2:-send-a-request-to-googles-oauth-2.0-server

**Comment by louisgv** [comment]
> @rafek1241 The loopback method is not being deprecated for desktop apps (only for android and ios).
> 
> @louisgv Thanks a lot for the follow up. It should be quite useful! But are you sure you're not using the loopback method? I can't see any other type of recommended flow for desktop applications that were using oob before: https://developers.google.com/identity/protocols/oauth2/native-app#step-2:-send-a-request-to-googles-oauth-2.0-server

Oops my bad, by "loopback method," I was thinking about the method used in the original guide, which used the `urn:ietf:wg:oauth:2.0:oob:auto` uri to return the tokens, which should be called "Manual copy/paste."  It is indeed using loopback for redirect_uri. Somehow my brain linked both `redirect_uri` and the `manual copy/paste` thingy to loopback xD

**Comment by louisgv** [comment]
Just released [gcp-refresh-token](https://www.npmjs.com/package/gcp-refresh-token), source code [here](https://github.com/plasmo-corp/gcp-refresh-token).

Let me know if you have any issue (preferably creating an issue under `gcp-refresh-token`). To use, download your OAuth Client json key into a `key.json` file, then run:

```
npx gcp-refresh-token

# or

pnpm dlx gcp-refresh-token
```

Refers to the [readme](https://github.com/plasmo-corp/gcp-refresh-token) for more info!

**Comment by poma** [comment]
Worked for me, thanks! This should be included in the docs now.

**Comment by louisgv** [comment]
@fregante done 👍

**Comment by fregante** [comment]
Please refer to the new guide in #63. You can temporarily read it at:

https://github.com/fregante/chrome-webstore-upload/blob/new-guide/How%20to%20generate%20Google%20API%20keys.md

The solution was to replace the _oob_ with a random `redirect_uri` on localhost, even if it doesn't exist + creating a "Desktop app" OAuth client.

Let me know if this works for you, this should be easier than running third party code on your machine and even saves a few steps!

**Comment by louisgv** [comment]
> Let me know if this works for you, this should be easier than running third party code on your machine ~and even saves a few steps!~

Although `gcp-refresh-token` is "third party code," it is open-sourced under MIT: https://github.com/plasmo-corp/gcp-refresh-token . I would love to have more fork auditing the source code! Please do not hesitate to file an issue :D 

Personally, I think in terms of ease of use, running `npx gcp-refresh-token` would be much faster than: `[ copy client_id, open browser to oauth code url, copy redeem code, exchange code for refresh token by copying js code into the browser repl ]`. 

I think the real issues with using `gcp-refresh-token`, looking from an outsider POV are:
1. The potential of a supply chain attack. To mitigate that, all dependencies are [frozen](https://github.com/plasmo-corp/gcp-refresh-token/blob/main/package.json). pnpm froze the version of all child dependencies as well.
2. The trustworthiness of `plasmo-corp` the org behind that module. (We're a 2 people startup working on browser extension dev tool). To mitigate this... it will take time xD - I think the more we build and the more we can prove that we come in peace, the community will gradually open up to us :p... (similar to building up my credit score, tho if anything I wish I had applied for my credit card much earlier xd)

**Comment by rafek1241** [comment]
@fregante I tried your way and last part (console script) didn't work for me.
![image](https://user-images.githubusercontent.com/9272027/163256829-0015218b-0db4-4036-b33c-d1f9747d0738.png)

After using a @louisgv solution: 
![image](https://user-images.githubusercontent.com/9272027/163256989-1d3266e9-c261-40d8-93fc-de6032c784ad.png)

Thanks

**Comment by fregante** [comment]
> I tried your way and last part (console script) didn't work for me.
> ![image](https://user-images.githubusercontent.com/9272027/163256829-0015218b-0db4-4036-b33c-d1f9747d0738.png)

@rafek1241 If you got that error, you enter the client ID incorrectly. I just tested it and I got "client secret" missing instead.


Were you able to publish the extension to the store with this new code? This change brings the `client secret` back into play and `chrome-webstore-upload` recently dropped support for it. If "Desktop app" requires it, this guide change isn't enough.

**Comment by fregante** [comment]
> it is open-sourced under MIT:

Licensing is not the issue and the code published to GitHub doesn't necessarily match what's on npm.



> 1. all dependencies are [frozen](https://github.com/plasmo-corp/gcp-refresh-token/blob/main/package.json?rgh-link-date=2022-04-13T08%3A50%3A19Z)

As I mentioned on your repo, that's not how npm works. All sub-dependencies cannot be frozen, the lockfile is not followed when installing/executing external packages.

> 2\. The trustworthiness of `plasmo-corp` the org behind that module

Got it, but running `npx anything` will concern some people. Best I could do is embed that tool into `chrome-webstore-upload-cli` itself. Plus it's not bug free (it's using a [private port](https://www.speedguide.net/port.php?port=1701)) and I'm not available to debug the whole package.

**Comment by louisgv** [comment]
> code published to GitHub doesn't necessarily match what's on npm.

How do you mitigate this issue with `chrome-webstore-upload`? Would love to learn more!

> Plus it's not bug free (it's using a [private port](https://www.speedguide.net/port.php?port=1701))

Since it uses https://www.npmjs.com/package/get-port, if 1701 isn't available, it will find a random one :p

**Comment by fregante** [comment]
> > code published to GitHub doesn't necessarily match what's on npm.
> 
> How do you mitigate this issue with `chrome-webstore-upload`? Would love to learn more!

I don't, but I'm not claiming that "my dependencies are frozen". There's no official way to do that other than:

- installing from GitHub like `npm install fregante/chrome-webstore-upload`
- using a third-party tool or service that verifies that, if it exists

**Comment by fregante** [comment]
As feared, using "Desktop app" fails the upload with:

```json
{
  "error": "invalid_request",
  "error_description": "client_secret is missing."
}
```

The client secret was dropped in v0.5.0 (#46) so if we revert back to "Desktop app" I'll also have to revert to using the client secret.

I tried using "Chrome app" while creating the new token but it does not natively accept `localhost` as a `redirect_uri`. 

- Has anyone had any success actually uploading the extension with `gcp-refresh-token`’s token?
- Does anyone know how to set `redirect_uri` to `localhost` with "Chrome app"?

**Comment by louisgv** [comment]
> > > code published to GitHub doesn't necessarily match what's on npm.
> > 
> > 
> > How do you mitigate this issue with `chrome-webstore-upload`? Would love to learn more!
> 
> I don't, but I'm not claiming that "my dependencies are frozen". There's no official way to do that other than:
> 
> * installing from GitHub like `npm install fregante/chrome-webstore-upload`
> * using a third-party tool or service that verifies that, if it exists

Got it - I will edit my claim as "pinned" instead of "frozen" :D

Tho, I wonder if there is a way to ensure that the published code on github is the code actually running from npm? Why can't npm just make a lock file when they ingest the package into their server lol xD...

**Comment by fregante** [comment]
I tested the whole workflow and it's now working: https://github.com/fregante/browser-extension-template/runs/6022135901?check_suite_focus=true


```
npm WARN exec The following package was not found and will be installed: chrome-webstore-upload-cli@2
- Fetching token
- Uploading distribution
- Publishing
Publish successful
```

Findings:

- the secret-less "Chrome app" was nice while it lasted; Google’s intent with that is to be used via `chrome.identity` in extensions, so we can't use it anymore
- the `client_secret` is now required again since we must use Desktop App
- I also tried "Web application" but it also required the secret in the end
- I updated the cli tool to output a better message when the secret is required: https://github.com/fregante/chrome-webstore-upload-cli/pull/60

Future:

- [ ] https://github.com/fregante/chrome-webstore-upload-cli/issues/61
