### ISSUE TITLE
Update store listing -  Product detail?

### ISSUE THREAD

**Issue by mirusu400** [fregante/chrome-webstore-upload#71]
![image](https://github.com/fregante/chrome-webstore-upload/assets/25397908/82ac25d7-04e9-41d4-87a7-4a2bd089e45c)

It should be better that we can also update store description detail - not only can publish new files.

**Comment by fregante** [comment]
I wish. Unfortunately the API I use is very limited: https://developer.chrome.com/docs/webstore/api_index/
