### ISSUE TITLE
Uploading a new extension publishes a previous version and not a new one

### ISSUE THREAD

**Issue by juan-hf** [fregante/chrome-webstore-upload#80]
I have the following code

```
import chromeWebstoreUpload from 'chrome-webstore-upload';
import chalk from 'chalk';
import fs from 'fs'; // Import the fs module
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';
import dotenv from 'dotenv';

// Initialize dotenv to load the .env variables
dotenv.config();

const argv = yargs(hideBin(process.argv)).argv;
const zipname = "./extension.zip";
const myZipFile = fs.createReadStream(zipname);

const webStore = chromeWebstoreUpload({
    clientId: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    refreshToken: process.env.REFRESH_TOKEN,
    extensionId: argv.extensionid
})

webStore.fetchToken()
    .then(token => {
        console.log(chalk.green("Token fetched"));
        webStore.uploadExisting(myZipFile, token).then(res => {
            webStore.publish().then(res => {
                console.log(chalk.green('Successfully published the newer version'));
                fs.unlink(zipname, (err) => {
                    if (err) throw err;
                    console.log(chalk.magenta('The ZIP file has been deleted'));
                });
            }).catch((error) => {
                console.log(`Error while publishing uploaded extension: ${error}`);
                process.exit(1);
            });
        });
    })
    .catch(error => {
        console.log(chalk.red('An error occurred:', error));
    }); 
 ```
    
- I'm using Node 20
- I'm using pnpm as packet manager

Issue:
- The extension publishes again the previous version of the Chrome extension
- It doesn't take into consideration the version that is in the manifest of the ZIPed extension files

Tests:
- I uploaded manually the exact same file and the process worked as expected, updating the code and version number of the new deployment that is inside the manifest

**Comment by fregante** [comment]
Note that there's a dedicated method to upload and publish, you can use that one.

**Comment by fregante** [comment]
I got confused with the cli version. 

Is there a specific reason to use this module instead of `chrome-webstore-upload-cli`? It takes care of everything in one line

**Comment by juan-hf** [comment]
Because I have some actions that happen before and after (for example I check if I forgot to change the manifest number) and I'd rather have 1 code to do everything, than having multiple node apps and a bash script that puts everything together.

**Comment by fregante** [comment]
I used this script just last week without issue: https://github.com/fregante/chrome-webstore-upload/blob/main/test/live-test.js


> It doesn't take into consideration the version that is in the manifest of the ZIPed extension files

`chrome-webstore-upload` doesn't read the zip file, it just sends it to the API and then it's the store that deals with it. 

Try using the .upload() method alone, after that one it should appear in the dashboard as a new draft version (wait a minute for it to update first)

.publish() just instructs the store to publish whatever version is in draft, so if the first step fails then this one won't do anything.

**Comment by juan-hf** [comment]
There's no `upload` method in your library

![Zight 2024-01-08 at 3 01 41 PM](https://github.com/fregante/chrome-webstore-upload/assets/99024140/211bfcc8-e2ef-421b-8a94-101c3604e4fd)

**Comment by fregante** [comment]
That's the one I meant

**Comment by juan-hf** [comment]
Ok I found the problem.
It came from the fact that the Zip file didn't follow the guidelines
So the script was republishing the version that was already published (by automatically recreating a draft) instead of taking into account the new one, that was never uploaded in the first place.

Thank you for your prompt help.

Best

**Comment by fregante** [comment]
I think the issue here was that this module does not handle errors by the API, because it responds with HTTP 200.

I opened an issue to improve that handling:

- https://github.com/fregante/chrome-webstore-upload/issues/83

I think the cli has some of this this built-in
