### ISSUE TITLE
Cannot upload to CWS 400 Bad Request

### ISSUE THREAD

**Issue by LuWang1983** [fregante/chrome-webstore-upload#88]
Hi! 
We've been using `chrome-webstore-upload` to upload our chrome extension for a while now and recently have consistently been getting a 400 Bad Request error for about 1.5 weeks whenever we tried to upload the extension. Initially we thought it was a transient error but it has yet to be resolved. Manually uploading the extension package has been successful.  

I tried to log out the error stack to have more context, unfortunately, all it says is `Bad Request` without any further helpful information. 

Here is the error from our GitHub Actions deployment pipeline:
```
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/home/debian/actions-runner/_work/castify/castify/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (internal/process/task_queues.js:[95](https://github.com/screencastify/castify/actions/runs/8298882997/job/22713298715#step:6:96):5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1710518525120,
    socket: 1710518525124,
    lookup: 1710518525157,
    connect: 1710518525159,
    secureConnect: 1710518525164,
    upload: 1710518525164,
    response: 1710518525233,
    end: 17[105](https://github.com/screencastify/castify/actions/runs/8298882997/job/22713298715#step:6:106)18525235,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 4,
      dns: 33,
      tcp: 2,
      tls: 5,
      request: 0,
      firstByte: 69,
      download: 2,
      total: [115](https://github.com/screencastify/castify/actions/runs/8298882997/job/22713298715#step:6:116)
    }
  }
}
```
And here is the code snippet of the deploy script:
```
  const cws = await getCwsClient(secrets, extensionId);
  // Generate zip on the fly from dist/ folder
  const zipStream = new PassThrough();
  const zipPromise = generateZip(
    { forCws: true, env: args.env as TEnvironment },
    zipStream,
  );
  const uploadResponse = await cws.uploadExisting(zipStream);
```

I double checked the OAuth client secret, it's in good standing and we've been using it for 3 years without an issue. It happens both locally on my machine and the GitHub Actions pipeline. 

Other triagings I've tried including trying a different `zipStream` by zipping the extension first and converting to a read stream using `fs.createReadStrem(<PATH_TO_ZIP>)` as instructed on the `README` since 400 Bad Request usually means the client data is no good, but resulting a 400 Bad Request as well; and updating the `chrome-webstore-upload` version (Unfortunately, this is deploying some legacy code so we can't go beyond 0.5.0). 

Please let me know if you've had other users reporting this issues lately. We have not changed the deploy script for quite some time but we did update the extension itself and we are looking to deploy it. 

The other possibility is the Google cws API endpoint has changed the way it processes data. I have not looked into it yet and successfully manually uploading the package on the Chrome Web Store told me it's not our zip file or the extension itself that has the problem. Please advise, thank you very much!

**Comment by fregante** [comment]
Please update the version you're using. This package hasn't used `got` in a while.

**Comment by fregante** [comment]
You can save the artifact in a job and then run the latest version of `chrome-webstore-upload-cli`. Your app's node version does not have to match the node version you use to deploy. 

You can refer to the readme of the CLI project for the suggested workflow. In my projects, I build once and then in a separate matrix job I publish to two stores.

**Comment by LuWang1983** [comment]
Thank you! I tested with Axios and the 400 errored at fetch token. Our secret credentials for some reason are no longer good. So it's not because of the lib `got`. Now the upload results a 403, even though access tokens are successfully generated with the correct scope, still not resolved but it's progress.
