### ISSUE TITLE
Issue: Obtain Current Extension Version through Google API

### ISSUE THREAD

**Issue by flazouh** [fregante/chrome-webstore-upload#96]
**Description:**

I am currently working on a project that involves managing Chrome extensions, and I need to programmatically obtain the current version of a Chrome extension. I have reviewed the available Google APIs but have not found a clear method to retrieve the current version of an extension.

**Request:**

Could you please provide guidance or confirm if it is possible to obtain the current version of a Chrome extension through the Google API via your package? If this feature is not currently available, I would like to request it as a new feature.

**Current Workaround:**

For the moment, I am using the following workaround to scrape the version number from the extension's web page:

```javascript
const response = await fetch(url, {
  headers: {
    'User-Agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
  },
});

const html = await response.text();
const $ = load(html);

let versionNumber: Nilable<string>;
$('div').each((index, element) => {
  const text = $(element).text().trim();
  if (text === 'Version') {
    versionNumber =
      $(element).next().text().trim() ||
      $(element).next().find('div').first().text().trim();
  }
});
return versionNumber || '';

**Comment by fregante** [comment]
It doesn't look like the API provides this piece of information, so it's not possible: https://developer.chrome.com/docs/webstore/api#get

**Comment by fregante** [comment]
There's a dedicated package for this, and they also fetch the HTML page and parse it:

https://github.com/awesome-webextension/webextension-store-meta/blob/main/src/chrome-web-store/index.ts

**Comment by flazouh** [comment]
I see thanks @fregante, what a shame that the api is so limited, what are they doing haha 😭
